// <auto-generated />
using System;
using ISBTest.DAL.DataProviders;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ISBTest.DAL.Migrations
{
    [DbContext(typeof(ISBTestDbContext))]
    [Migration("20240704163727_AddPropertyTable")]
    partial class AddPropertyTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ISBTest.DAL.Entities.Property", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateOfRegistration")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Price")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Property");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bf987682-1335-4ecb-808d-51c6bf3a7ed3"),
                            Address = "Address 1",
                            CreatedAt = new DateTime(2024, 7, 4, 16, 37, 26, 902, DateTimeKind.Utc).AddTicks(7805),
                            DateOfRegistration = new DateTime(2024, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Name 1",
                            Price = "USD 10000.00",
                            UpdatedAt = new DateTime(2024, 7, 4, 16, 37, 26, 902, DateTimeKind.Utc).AddTicks(7806)
                        },
                        new
                        {
                            Id = new Guid("fe9e1bb2-1528-429b-909f-71d7126285e1"),
                            Address = "Address 2",
                            CreatedAt = new DateTime(2024, 7, 4, 16, 37, 26, 902, DateTimeKind.Utc).AddTicks(7818),
                            DateOfRegistration = new DateTime(2024, 7, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Name 2",
                            Price = "USD 20000.00",
                            UpdatedAt = new DateTime(2024, 7, 4, 16, 37, 26, 902, DateTimeKind.Utc).AddTicks(7819)
                        },
                        new
                        {
                            Id = new Guid("cbe6114c-7a72-400b-98fa-86d725a8cb22"),
                            Address = "Address 3",
                            CreatedAt = new DateTime(2024, 7, 4, 16, 37, 26, 902, DateTimeKind.Utc).AddTicks(7821),
                            DateOfRegistration = new DateTime(2024, 7, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Name 3",
                            Price = "USD 30000.00",
                            UpdatedAt = new DateTime(2024, 7, 4, 16, 37, 26, 902, DateTimeKind.Utc).AddTicks(7821)
                        },
                        new
                        {
                            Id = new Guid("872a1a41-cb52-4db9-ac88-4e04ddb5e67d"),
                            Address = "Address 4",
                            CreatedAt = new DateTime(2024, 7, 4, 16, 37, 26, 902, DateTimeKind.Utc).AddTicks(7834),
                            DateOfRegistration = new DateTime(2024, 7, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Name 4",
                            Price = "USD 40000.00",
                            UpdatedAt = new DateTime(2024, 7, 4, 16, 37, 26, 902, DateTimeKind.Utc).AddTicks(7835)
                        },
                        new
                        {
                            Id = new Guid("b456b0aa-57cf-4d84-82e9-6347c3c6dcf1"),
                            Address = "Address 5",
                            CreatedAt = new DateTime(2024, 7, 4, 16, 37, 26, 902, DateTimeKind.Utc).AddTicks(7838),
                            DateOfRegistration = new DateTime(2024, 7, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Name 5",
                            Price = "USD 50000.00",
                            UpdatedAt = new DateTime(2024, 7, 4, 16, 37, 26, 902, DateTimeKind.Utc).AddTicks(7838)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
